### ISSUE TITLE
Error messages are confusing when types are not correctly parenthesized

### ISSUE THREAD

**Issue by JasonGross** [ppedrot/ltac2#111] opened 2019-03-11 02:10 UTC
"This expression has type unit -> unit list but an expression was expected of type unit -> unit list"
```coq
Require Import Ltac2.Ltac2.
Require Import Ltac2.Control.
Require Import Ltac2.Notations.

Goal True /\ 0 = 0.
  split; Control.dispatch (fun () => [Control.plus (fun _ => exact I) (fun _ => exact eq_refl)]).
  (* Error:
This expression has type unit -> unit list but an expression was expected of type
unit -> unit list
*)
```

**Comment by ppedrot** [comment] 2019-03-11 07:59
Duplicate of #103

**Closed by ppedrot** 2019-03-11 07:59 UTC
